# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: PowerShell@2
  displayName: "Get Changesets"
  inputs:
    targetType: 'inline'
    script: |
      git log --oneline
      $values = git log -n 2
      Write-Host $values

# - task: PowerShell@2
#   displayName: "Get and Compare Changesets"
#   inputs:
#     targetType: 'inline'
#     script: |
#       $changedFiles = git diff --name-only -r $(Build.SourceVersion)
#       Write-Host $changedFiles
#       Write-Output $changedFiles > $(Build.ArtifactStagingDirectory)/changedFiles.txt
      

# - task: PowerShell@2
#   displayName: "Get and Compare Changesets"
#   inputs:
#     targetType: 'inline'
#     script: |
#       $val = git log -n 2 --format=%h
#       $changeSets = git log -n 2 --format=%h
#       $changedFiles = (git diff --name-only $changeSets[0] $changeSets[1])



# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
#     ArtifactName: 'drop'
#     publishLocation: 'Container'
